services:


  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: week_17_exam
      MYSQL_USER: admin         
      MYSQL_PASSWORD: 12345678 
    volumes:
      - mysql_data:/var/lib/mysql

    
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db


  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: social_commerce_kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LISTENERS: >
        PLAINTEXT://0.0.0.0:9092,
        INTERNAL://0.0.0.0:29092,
        CONTROLLER://0.0.0.0:29093

      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT://localhost:9092,
        INTERNAL://kafka:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        PLAINTEXT:PLAINTEXT,
        INTERNAL:PLAINTEXT,
        CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka_data:/var/lib/kafka/data
  # networks:
  #   - social_commerce_network

  # FastAPI application
  # app:
  #   build:
  #     context: ./apps/mongo_backend
  #     dockerfile: Dockerfile
  #   container_name: social_commerce_app
  #   restart: unless-stopped
  #   ports:
  #     - "8000:8000"
    # environment:
    #   - MONGODB_URL=mongodb://mongodb:27017
    #   - DATABASE_NAME=social_commerce
    #   - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    #   - KAFKA_CLIENT_ID=backend-service
    # depends_on:
      # - mongodb
      # - kafka
    # networks:
    #   - social_commerce_network
    # volumes:
      # - ./apps/mongo_backend:/app
      # - ./shared:/app/shared



  # MySQL Analytics Service (Kafka Consumer)
  # mysql-service:
  #   build:
  #     context: ./apps/mysql_server
  #     dockerfile: Dockerfile
  #   container_name: social_commerce_mysql_service
  #   restart: unless-stopped
  #   # environment:
  #   #   - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
  #   #   - KAFKA_CLIENT_ID=mysql-service
  #   #   - KAFKA_GROUP_ID=mysql-analytics-service

  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #     kafka:
  #       condition: service_started
  #   networks:
  #     - social_commerce_network
  #   # volumes:
  #     - ./apps/mysql_server:/app
  #     - ./shared:/app/shared

# networks:
#   social_commerce_network:
#     driver: bridge

volumes:
  mysql_data:
    driver: local
  mongodb_data:
    driver: local
  kafka_data:
    driver: local



